server:
  port: ${PORT:9002}
spring:
  kafka:
    consumer:
      bootstrap-servers: ${DNSPORT}:9092
      group-id: jacek-japila-pl
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


